# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# The setting below is for the github pages default domain name.
# For the custom TLD, this will be all served from root, as it is on
# the local dev configuration.
#baseurl: "design4democracy" # the subpath of your site, e.g. /blog

google_site_verification: ""

# Google Analytics
google_analytics: UA-120811815-1

# SEO Overrides
url: "https://d4dcoalition.org"
logo: "/assets/img/logos/d4d-logo.png"


# If using Facebook Insights
facebook:
  app_id:
  publisher:
  admins:

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - assets/templates/ # https://pixelarity.com/license
